#include "board_port.h"

#define BIT_SENSOR_L2 (1U << 0)
#define BIT_SENSOR_L1 (1U << 1)
#define BIT_SENSOR_C  (1U << 2)
#define BIT_SENSOR_R1 (1U << 3)
#define BIT_SENSOR_R2 (1U << 4)

/*
 * Replace these four macros with the PWM names generated by your SysConfig.
 * Example names often look like PWM_0_INST and DL_TIMER_CC_0_INDEX, but the
 * exact symbols depend on your timer and channel names.
 */
#ifndef LEFT_PWM_INST
#define LEFT_PWM_INST PWM_0_INST
#endif

#ifndef LEFT_PWM_CC_INDEX
#define LEFT_PWM_CC_INDEX DL_TIMER_CC_0_INDEX
#endif

#ifndef RIGHT_PWM_INST
#define RIGHT_PWM_INST PWM_0_INST
#endif

#ifndef RIGHT_PWM_CC_INDEX
#define RIGHT_PWM_CC_INDEX DL_TIMER_CC_1_INDEX
#endif

static void set_pwm_duty(GPTIMER_Regs *timer, DL_TIMER_CC_INDEX cc_index, uint16_t duty)
{
    if (duty > MOTOR_PWM_PERIOD_COUNTS) {
        duty = MOTOR_PWM_PERIOD_COUNTS;
    }

    DL_TimerG_setCaptureCompareValue(timer,
                                     MOTOR_PWM_PERIOD_COUNTS - duty,
                                     cc_index);
}

static void set_left_direction(bool forward)
{
    if (forward) {
        DL_GPIO_setPins(MOTOR_AIN1_PORT, MOTOR_AIN1_PIN);
        DL_GPIO_clearPins(MOTOR_AIN2_PORT, MOTOR_AIN2_PIN);
    } else {
        DL_GPIO_clearPins(MOTOR_AIN1_PORT, MOTOR_AIN1_PIN);
        DL_GPIO_setPins(MOTOR_AIN2_PORT, MOTOR_AIN2_PIN);
    }
}

static void set_right_direction(bool forward)
{
    if (forward) {
        DL_GPIO_setPins(MOTOR_BIN1_PORT, MOTOR_BIN1_PIN);
        DL_GPIO_clearPins(MOTOR_BIN2_PORT, MOTOR_BIN2_PIN);
    } else {
        DL_GPIO_clearPins(MOTOR_BIN1_PORT, MOTOR_BIN1_PIN);
        DL_GPIO_setPins(MOTOR_BIN2_PORT, MOTOR_BIN2_PIN);
    }
}

void Board_init(void)
{
    SYSCFG_DL_init();

#ifdef MOTOR_STBY_PIN
    DL_GPIO_setPins(MOTOR_STBY_PORT, MOTOR_STBY_PIN);
#endif

    DL_TimerG_startCounter(LEFT_PWM_INST);
    DL_TimerG_startCounter(RIGHT_PWM_INST);
}

uint8_t Board_readGray5(void)
{
    uint8_t bits = 0;

#if GRAY_BLACK_IS_LOW
    if ((DL_GPIO_readPins(GRAY_L2_PORT, GRAY_L2_PIN) & GRAY_L2_PIN) == 0U) { bits |= BIT_SENSOR_L2; }
    if ((DL_GPIO_readPins(GRAY_L1_PORT, GRAY_L1_PIN) & GRAY_L1_PIN) == 0U) { bits |= BIT_SENSOR_L1; }
    if ((DL_GPIO_readPins(GRAY_C_PORT, GRAY_C_PIN) & GRAY_C_PIN) == 0U) { bits |= BIT_SENSOR_C; }
    if ((DL_GPIO_readPins(GRAY_R1_PORT, GRAY_R1_PIN) & GRAY_R1_PIN) == 0U) { bits |= BIT_SENSOR_R1; }
    if ((DL_GPIO_readPins(GRAY_R2_PORT, GRAY_R2_PIN) & GRAY_R2_PIN) == 0U) { bits |= BIT_SENSOR_R2; }
#else
    if ((DL_GPIO_readPins(GRAY_L2_PORT, GRAY_L2_PIN) & GRAY_L2_PIN) != 0U) { bits |= BIT_SENSOR_L2; }
    if ((DL_GPIO_readPins(GRAY_L1_PORT, GRAY_L1_PIN) & GRAY_L1_PIN) != 0U) { bits |= BIT_SENSOR_L1; }
    if ((DL_GPIO_readPins(GRAY_C_PORT, GRAY_C_PIN) & GRAY_C_PIN) != 0U) { bits |= BIT_SENSOR_C; }
    if ((DL_GPIO_readPins(GRAY_R1_PORT, GRAY_R1_PIN) & GRAY_R1_PIN) != 0U) { bits |= BIT_SENSOR_R1; }
    if ((DL_GPIO_readPins(GRAY_R2_PORT, GRAY_R2_PIN) & GRAY_R2_PIN) != 0U) { bits |= BIT_SENSOR_R2; }
#endif

    return bits;
}

void Board_setMotorSpeed(int16_t left_speed, int16_t right_speed)
{
    bool left_forward = (left_speed >= 0);
    bool right_forward = (right_speed >= 0);
    uint16_t left_duty = (uint16_t) (left_forward ? left_speed : -left_speed);
    uint16_t right_duty = (uint16_t) (right_forward ? right_speed : -right_speed);

    set_left_direction(left_forward);
    set_right_direction(right_forward);
    set_pwm_duty(LEFT_PWM_INST, LEFT_PWM_CC_INDEX, left_duty);
    set_pwm_duty(RIGHT_PWM_INST, RIGHT_PWM_CC_INDEX, right_duty);
}

void Board_setBuzzer(bool on)
{
    if (on) {
        DL_GPIO_setPins(BEEP_PORT, BEEP_PIN);
    } else {
        DL_GPIO_clearPins(BEEP_PORT, BEEP_PIN);
    }
}

void Board_delayMs(uint32_t ms)
{
    while (ms-- > 0U) {
        delay_cycles(CPUCLK_FREQ / 1000U);
    }
}
